server:
  port: 8081

logging:
  level:
    org.springframework: DEBUG

spring:
  security:
    user:
      name: username
      password: 1121
  messages:
    basename: messages

management:
  endpoints:
    web:
      exposure:
        include: "*"